---
name: "Discogs"
guid: "983c0fbd-d662-41e0-b85c-99d71f1b3935"
version: "0.1.1.0"
targetAbi: "10.8.13.0"
framework: "net6.0"
overview: "Discogs music metadata provider"
description: >
  Integrate with the Discogs database for music metadata
category: "Metadata"
owner: "Tob-Knob"
artifacts:
  - "Jellyfin.Plugin.Discogs.dll"
  - "DiscogsClient.dll"
changelog: >
  changelog
